import "../styles/globals.css";
import { Provider } from "react-redux";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Layout } from "@layout";
import { store } from "@store";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </Provider>
    </>
  );
}

export default MyApp;
