import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { RootStoreProvider } from "../context";
import { Layout } from "../components";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootStoreProvider hydrationData={pageProps.hydrationData}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </RootStoreProvider>
    </>
  );
}

export default MyApp;
