import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
      <div>Homepage</div>
    </>
  );
};

export default Home;
